package com.applovin.impl;

import com.applovin.impl.p4;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;
/* compiled from: Proguard */
/* loaded from: classes3.dex */
public abstract class g3 extends l4 {
    public static final l4 A7;
    public static final l4 B7;
    public static final l4 C7;
    public static final l4 D7;
    public static final l4 E7;
    public static final l4 F7;
    public static final l4 G7;
    public static final l4 H7;
    public static final l4 I6 = l4.a("afi", "");
    public static final l4 I7;
    public static final l4 J6;
    public static final l4 J7;
    public static final l4 K6;
    public static final l4 K7;
    public static final l4 L6;
    public static final l4 L7;
    public static final l4 M6;
    public static final l4 M7;
    public static final l4 N6;
    public static final l4 N7;
    public static final l4 O6;
    public static final l4 O7;
    public static final l4 P6;
    public static final l4 P7;
    public static final l4 Q6;
    public static final l4 Q7;
    public static final l4 R6;
    public static final l4 R7;
    public static final l4 S6;
    public static final l4 S7;
    public static final l4 T6;
    public static final l4 T7;
    public static final l4 U6;
    public static final l4 U7;
    public static final l4 V6;
    public static final l4 W6;
    public static final l4 X6;
    public static final l4 Y6;
    public static final l4 Z6;
    public static final l4 a7;
    public static final l4 b7;
    public static final l4 c7;
    public static final l4 d7;
    public static final l4 e7;
    public static final l4 f7;
    public static final l4 g7;
    public static final l4 h7;
    public static final l4 i7;
    public static final l4 j7;
    public static final l4 k7;
    public static final l4 l7;
    public static final l4 m7;
    public static final l4 n7;
    public static final l4 o7;
    public static final l4 p7;
    public static final l4 q7;
    public static final l4 r7;
    public static final l4 s7;
    public static final l4 t7;
    public static final l4 u7;
    public static final l4 v7;
    public static final l4 w7;
    public static final l4 x7;
    public static final l4 y7;
    public static final l4 z7;

    static {
        Boolean bool = Boolean.FALSE;
        J6 = l4.a("iafiwaa", bool);
        TimeUnit timeUnit = TimeUnit.SECONDS;
        K6 = l4.a("afi_ms", Long.valueOf(timeUnit.toMillis(5L)));
        L6 = l4.a("mediation_endpoint", "https://ms.applovin.com/");
        M6 = l4.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        N6 = l4.a("fetch_next_ad_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        O6 = l4.a("fetch_next_ad_timeout_ms", Long.valueOf(timeUnit.toMillis(30L)));
        P6 = l4.a("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(timeUnit.toMillis(7L)));
        Boolean bool2 = Boolean.TRUE;
        Q6 = l4.a("auto_init_mediation_debugger", bool2);
        R6 = l4.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        S6 = l4.a("max_signal_provider_latency_ms", Long.valueOf(timeUnit.toMillis(30L)));
        T6 = l4.a("default_adapter_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        U6 = l4.a("ad_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        V6 = l4.a("ad_load_failure_refresh_ms", Long.valueOf(timeUnit.toMillis(30L)));
        W6 = l4.a("ad_load_failure_refresh_ignore_error_codes", "204");
        X6 = l4.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        Y6 = l4.a("refresh_ad_view_timer_responds_to_background", bool2);
        Z6 = l4.a("refresh_ad_view_timer_responds_to_store_kit", bool2);
        a7 = l4.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool);
        b7 = l4.a("avrsponse", bool);
        c7 = l4.a("allow_pause_auto_refresh_immediately", bool);
        d7 = l4.a("ad_view_race_condition_fix_enabled", bool);
        e7 = l4.a("always_destroy_ad_view_on_ui_thread", bool);
        f7 = l4.a("fullscreen_display_delay_ms", 0L);
        g7 = l4.a("susaode", bool);
        h7 = l4.a("ahdm", 500L);
        i7 = l4.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        j7 = l4.a("ad_view_refresh_precache_request_enabled", bool2);
        k7 = l4.a("famttl_ms", 0L);
        l7 = l4.a("signal_expiration_ms", -1L);
        m7 = l4.a("signal_cache_level", Integer.valueOf(p4.b.AD_FORMAT.ordinal()));
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        n7 = l4.a("ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        o7 = l4.a("native_ad_expiration_ms", Long.valueOf(timeUnit2.toMillis(4L)));
        p7 = l4.a("rena", bool2);
        q7 = l4.a("fullscreen_ad_displayed_timeout_ms", -1L);
        r7 = l4.a("freast_ms", -1L);
        s7 = l4.a("ad_hidden_timeout_ms", -1L);
        t7 = l4.a("schedule_ad_hidden_on_ad_dismiss", bool);
        u7 = l4.a("schedule_ad_hidden_on_single_task_app_relaunch", bool);
        v7 = l4.a("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        w7 = l4.a("proe", bool);
        x7 = l4.a("teatfmacc", bool);
        y7 = l4.a("mute_state", 2);
        z7 = l4.a("saf", "");
        A7 = l4.a("saui", "");
        B7 = l4.a("malm_v2_e", bool);
        C7 = l4.a("mspc", 1);
        D7 = l4.a("mra", -1);
        E7 = l4.a("mra_af", "INTER,REWARDED,BANNER,LEADER,MREC");
        F7 = l4.a("fadiafase", bool2);
        G7 = l4.a("fadwvcv", bool2);
        H7 = l4.a("bfarud", bool);
        I7 = l4.a("inacc", Boolean.valueOf(z6.b(Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        J7 = l4.a("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        K7 = l4.a("faomq", bool);
        L7 = l4.a("rahcnct_sec", -1);
        M7 = l4.a("uabta", bool);
        N7 = l4.a("use_initialization_spec_during_init", bool);
        O7 = l4.a("report_cimp_after_ierr", bool);
        P7 = l4.a("fail_collection_for_empty_signal", bool);
        Q7 = l4.a("fetch_mediated_ad_gzip", bool2);
        R7 = l4.a("max_postback_gzip", bool2);
        S7 = l4.a("md_endpoint", "https://md.applovin.com/");
        T7 = l4.a("md_backup_endpoint", "https://md.applvn.com/");
        U7 = l4.a("md_v2", bool);
    }
}
