package com.applovin.impl;

import androidx.media3.common.C;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.impl.i4;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.tencent.thumbplayer.tcmedia.core.downloadproxy.api.TPDownloadProxyEnum;
import com.vungle.ads.internal.protos.Sdk;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
/* compiled from: Proguard */
/* loaded from: classes3.dex */
public class l4 implements Comparable {
    public static final l4 A;
    public static final l4 A0;
    public static final l4 A1;
    public static final l4 A2;
    public static final l4 A3;
    public static final l4 A4;
    public static final l4 A5;
    public static final l4 A6;
    public static final l4 B;
    public static final l4 B0;
    public static final l4 B1;
    public static final l4 B2;
    public static final l4 B3;
    public static final l4 B4;
    public static final l4 B5;
    public static final l4 B6;
    public static final l4 C;
    public static final l4 C0;
    public static final l4 C1;
    public static final l4 C2;
    public static final l4 C3;
    public static final l4 C4;
    public static final l4 C5;
    public static final l4 C6;
    public static final l4 D;
    public static final l4 D0;
    public static final l4 D1;
    public static final l4 D2;
    public static final l4 D3;
    public static final l4 D4;
    public static final l4 D5;
    public static final l4 D6;
    public static final l4 E;
    public static final l4 E0;
    public static final l4 E1;
    public static final l4 E2;
    public static final l4 E3;
    public static final l4 E4;
    public static final l4 E5;
    public static final l4 E6;
    public static final l4 F;
    public static final l4 F0;
    public static final l4 F1;
    public static final l4 F2;
    public static final l4 F3;
    public static final l4 F4;
    public static final l4 F5;
    public static final l4 F6;
    public static final l4 G;
    public static final l4 G0;
    public static final l4 G1;
    public static final l4 G2;
    public static final l4 G3;
    public static final l4 G4;
    public static final l4 G5;
    public static final l4 G6;
    public static final l4 H;
    public static final l4 H0;
    public static final l4 H1;
    public static final l4 H2;
    public static final l4 H3;
    public static final l4 H4;
    public static final l4 H5;
    public static final l4 H6;
    public static final l4 I;
    public static final l4 I0;
    public static final l4 I1;
    public static final l4 I2;
    public static final l4 I3;
    public static final l4 I4;
    public static final l4 I5;
    public static final l4 J;
    public static final l4 J0;
    public static final l4 J1;
    public static final l4 J2;
    public static final l4 J3;
    public static final l4 J4;
    public static final l4 J5;
    public static final l4 K;
    public static final l4 K0;
    public static final l4 K1;
    public static final l4 K2;
    public static final l4 K3;
    public static final l4 K4;
    public static final l4 K5;
    public static final l4 L;
    public static final l4 L0;
    public static final l4 L1;
    public static final l4 L2;
    public static final l4 L3;
    public static final l4 L4;
    public static final l4 L5;
    public static final l4 M;
    public static final l4 M0;
    public static final l4 M1;
    public static final l4 M2;
    public static final l4 M3;
    public static final l4 M4;
    public static final l4 M5;
    public static final l4 N;
    public static final l4 N0;
    public static final l4 N1;
    public static final l4 N2;
    public static final l4 N3;
    public static final l4 N4;
    public static final l4 N5;
    public static final l4 O;
    public static final l4 O0;
    public static final l4 O1;
    public static final l4 O2;
    public static final l4 O3;
    public static final l4 O4;
    public static final l4 O5;
    public static final l4 P;
    public static final l4 P0;
    public static final l4 P1;
    public static final l4 P2;
    public static final l4 P3;
    public static final l4 P4;
    public static final l4 P5;
    public static final l4 Q;
    public static final l4 Q0;
    public static final l4 Q1;
    public static final l4 Q2;
    public static final l4 Q3;
    public static final l4 Q4;
    public static final l4 Q5;
    public static final l4 R;
    public static final l4 R0;
    public static final l4 R1;
    public static final l4 R2;
    public static final l4 R3;
    public static final l4 R4;
    public static final l4 R5;
    public static final l4 S;
    public static final l4 S0;
    public static final l4 S1;
    public static final l4 S2;
    public static final l4 S3;
    public static final l4 S4;
    public static final l4 S5;
    public static final l4 T;
    public static final l4 T0;
    public static final l4 T1;
    public static final l4 T2;
    public static final l4 T3;
    public static final l4 T4;
    public static final l4 T5;
    public static final l4 U;
    public static final l4 U0;
    public static final l4 U1;
    public static final l4 U2;
    public static final l4 U3;
    public static final l4 U4;
    public static final l4 U5;
    public static final l4 V;
    public static final l4 V0;
    public static final l4 V1;
    public static final l4 V2;
    public static final l4 V3;
    public static final l4 V4;
    public static final l4 V5;
    public static final l4 W;
    public static final l4 W0;
    public static final l4 W1;
    public static final l4 W2;
    public static final l4 W3;
    public static final l4 W4;
    public static final l4 W5;
    public static final l4 X;
    public static final l4 X0;
    public static final l4 X1;
    public static final l4 X2;
    public static final l4 X3;
    public static final l4 X4;
    public static final l4 X5;
    public static final l4 Y;
    public static final l4 Y0;
    public static final l4 Y1;
    public static final l4 Y2;
    public static final l4 Y3;
    public static final l4 Y4;
    public static final l4 Y5;
    public static final l4 Z;
    public static final l4 Z0;
    public static final l4 Z1;
    public static final l4 Z2;
    public static final l4 Z3;
    public static final l4 Z4;
    public static final l4 Z5;
    public static final l4 a0;
    public static final l4 a1;
    public static final l4 a2;
    public static final l4 a3;
    public static final l4 a4;
    public static final l4 a5;
    public static final l4 a6;
    public static final l4 b0;
    public static final l4 b1;
    public static final l4 b2;
    public static final l4 b3;
    public static final l4 b4;
    public static final l4 b5;
    public static final l4 b6;
    public static final l4 c0;
    public static final l4 c1;
    public static final l4 c2;
    public static final l4 c3;
    public static final l4 c4;
    public static final l4 c5;
    public static final l4 c6;
    public static final l4 d0;
    public static final l4 d1;
    public static final l4 d2;
    public static final l4 d3;
    public static final l4 d4;
    public static final l4 d5;
    public static final l4 d6;
    public static final l4 e;
    public static final l4 e0;
    public static final l4 e1;
    public static final l4 e2;
    public static final l4 e3;
    public static final l4 e4;
    public static final l4 e5;
    public static final l4 e6;
    public static final l4 f;
    public static final l4 f0;
    public static final l4 f1;
    public static final l4 f2;
    public static final l4 f3;
    public static final l4 f4;
    public static final l4 f5;
    public static final l4 f6;
    public static final l4 g;
    public static final l4 g0;
    public static final l4 g1;
    public static final l4 g2;
    public static final l4 g3;
    public static final l4 g4;
    public static final l4 g5;
    public static final l4 g6;
    public static final l4 h;
    public static final l4 h0;
    public static final l4 h1;
    public static final l4 h2;
    public static final l4 h3;
    public static final l4 h4;
    public static final l4 h5;
    public static final l4 h6;
    public static final l4 i;
    public static final l4 i0;
    public static final l4 i1;
    public static final l4 i2;
    public static final l4 i3;
    public static final l4 i4;
    public static final l4 i5;
    public static final l4 i6;
    public static final l4 j;
    public static final l4 j0;
    public static final l4 j1;
    public static final l4 j2;
    public static final l4 j3;
    public static final l4 j4;
    public static final l4 j5;
    public static final l4 j6;
    public static final l4 k;
    public static final l4 k0;
    public static final l4 k1;
    public static final l4 k2;
    public static final l4 k3;
    public static final l4 k4;
    public static final l4 k5;
    public static final l4 k6;
    public static final l4 l;
    public static final l4 l0;
    public static final l4 l1;
    public static final l4 l2;
    public static final l4 l3;
    public static final l4 l4;
    public static final l4 l5;
    public static final l4 l6;
    public static final l4 m;
    public static final l4 m0;
    public static final l4 m1;
    public static final l4 m2;
    public static final l4 m3;
    public static final l4 m4;
    public static final l4 m5;
    public static final l4 m6;
    public static final l4 n;
    public static final l4 n0;
    public static final l4 n1;
    public static final l4 n2;
    public static final l4 n3;
    public static final l4 n4;
    public static final l4 n5;
    public static final l4 n6;
    public static final l4 o;
    public static final l4 o0;
    public static final l4 o1;
    public static final l4 o2;
    public static final l4 o3;
    public static final l4 o4;
    public static final l4 o5;
    public static final l4 o6;
    public static final l4 p;
    public static final l4 p0;
    public static final l4 p1;
    public static final l4 p2;
    public static final l4 p3;
    public static final l4 p4;
    public static final l4 p5;
    public static final l4 p6;
    public static final l4 q;
    public static final l4 q0;
    public static final l4 q1;
    public static final l4 q2;
    public static final l4 q3;
    public static final l4 q4;
    public static final l4 q5;
    public static final l4 q6;
    public static final l4 r;
    public static final l4 r0;
    public static final l4 r1;
    public static final l4 r2;
    public static final l4 r3;
    public static final l4 r4;
    public static final l4 r5;
    public static final l4 r6;
    public static final l4 s;
    public static final l4 s0;
    public static final l4 s1;
    public static final l4 s2;
    public static final l4 s3;
    public static final l4 s4;
    public static final l4 s5;
    public static final l4 s6;
    public static final l4 t;
    public static final l4 t0;
    public static final l4 t1;
    public static final l4 t2;
    public static final l4 t3;
    public static final l4 t4;
    public static final l4 t5;
    public static final l4 t6;
    public static final l4 u;
    public static final l4 u0;
    public static final l4 u1;
    public static final l4 u2;
    public static final l4 u3;
    public static final l4 u4;
    public static final l4 u5;
    public static final l4 u6;
    public static final l4 v;
    public static final l4 v0;
    public static final l4 v1;
    public static final l4 v2;
    public static final l4 v3;
    public static final l4 v4;
    public static final l4 v5;
    public static final l4 v6;
    public static final l4 w;
    public static final l4 w0;
    public static final l4 w1;
    public static final l4 w2;
    public static final l4 w3;
    public static final l4 w4;
    public static final l4 w5;
    public static final l4 w6;
    public static final l4 x;
    public static final l4 x0;
    public static final l4 x1;
    public static final l4 x2;
    public static final l4 x3;
    public static final l4 x4;
    public static final l4 x5;
    public static final l4 x6;
    public static final l4 y;
    public static final l4 y0;
    public static final l4 y1;
    public static final l4 y2;
    public static final l4 y3;
    public static final l4 y4;
    public static final l4 y5;
    public static final l4 y6;
    public static final l4 z;
    public static final l4 z0;
    public static final l4 z1;
    public static final l4 z2;
    public static final l4 z3;
    public static final l4 z4;
    public static final l4 z5;
    public static final l4 z6;

    /* renamed from: a  reason: collision with root package name */
    private final String f3179a;
    private final Object b;
    private static final List c = Arrays.asList(Boolean.class, Float.class, Double.class, Integer.class, Long.class, String.class);
    private static final Map d = new HashMap(512);

    static {
        Boolean bool = Boolean.FALSE;
        e = a("is_disabled", bool);
        f = a(TPDownloadProxyEnum.USER_DEVICE_ID, "");
        Boolean bool2 = Boolean.TRUE;
        g = a("rss", bool2);
        h = a("rssoitf", bool);
        i = a("cpoitf", bool);
        j = a("device_token", "");
        k = a("is_verbose_logging", bool);
        l = a("sc", "");
        m = a("sc2", "");
        n = a("sc3", "");
        o = a("server_installed_at", "");
        p = a("clear_completion_callback_on_failure", bool);
        q = a("sicd_ms", 0L);
        r = a("logcat_max_line_size", 1000);
        s = a("exception_handler_enabled", bool2);
        t = a("md", "");
        u = a("ps_atu", "");
        v = a("lsu", bool);
        w = a("tla_ms", -1L);
        x = a("uactlac", bool);
        y = a("vsk", bool);
        z = a("error_reporter_v1_sample_percent", 100);
        A = a("health_events_reporter_v1_endpoint", "https://sts.applovin.com/v1/stats/sdk");
        B = a("health_events_reporter_v1_event_level_sampling_percentages", "");
        Float valueOf = Float.valueOf(-1.0f);
        C = a("health_events_reporter_v1_ad_sampling_percent", valueOf);
        D = a("health_events_reporter_v1_error_sampling_percent", valueOf);
        E = a("health_events_reporter_v1_user_session_sampling_percent", valueOf);
        F = a("health_events_reporter_v1_sampling_percent", Float.valueOf(1.0f));
        G = a("health_events_reporter_v1_batch_grouped_events", bool);
        H = a("health_events_reporter_should_skip_al_events_in_max", bool);
        I = a("health_events_reporter_valid_network_status_codes", "");
        J = a("health_events_reporter_include_cached_asset_info", bool);
        K = a("health_events_reporter_include_html_source", bool);
        L = a("stps", 2);
        M = a("auxiliary_operations_threads", 1);
        N = a("apsobt", bool2);
        O = a("tmtp", 1);
        P = a("network_thread_count", 2);
        Q = a("ntp", 5);
        R = a("ueq", bool);
        S = a("coretc", 1);
        T = a("cachetc", 1);
        U = a("mtc", 1);
        V = a("ttc", 1);
        W = a("otc", 1);
        X = a("uaeq", bool);
        Y = a("ubsm", bool);
        Z = a("ah_cvc", bool2);
        a0 = a("ah_cdde", bool2);
        b0 = a("ah_crut", bool2);
        c0 = a("ah_sae", bool2);
        d0 = a("ah_mvcwges", -1);
        e0 = a("init_omsdk", bool2);
        f0 = a("omsdk_partner_name", "applovin");
        TimeUnit timeUnit = TimeUnit.SECONDS;
        g0 = a("ttc_max_click_duration_ms", Long.valueOf(timeUnit.toMillis(1L)));
        h0 = a("ttc_max_click_distance_dp", 10);
        AppLovinTouchToClickListener.ClickRecognitionState clickRecognitionState = AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN;
        i0 = a("ttc_acrsv2a", Integer.valueOf(clickRecognitionState.ordinal()));
        j0 = a("ttc_acrsnv", Integer.valueOf(clickRecognitionState.ordinal()));
        k0 = a("ttc_acrsn", Integer.valueOf(clickRecognitionState.ordinal()));
        l0 = a("ttc_edge_buffer_dp", 0);
        m0 = a("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
        n0 = a("fetch_settings_endpoint", "https://ms.applovin.com/");
        o0 = a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
        p0 = a("adserver_endpoint", "https://a.applovin.com/");
        q0 = a("adserver_backup_endpoint", "https://a.applvn.com/");
        r0 = a("api_endpoint", "https://d.applovin.com/");
        s0 = a("api_backup_endpoint", "https://d.applvn.com/");
        t0 = a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
        u0 = a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
        v0 = a("eete", "https://b.applovin.com/");
        w0 = a("eetbe", "");
        x0 = a("webview_network_error_endpoints_to_report", "applovin.com,applvn.com");
        y0 = a("token_type_prefixes_r", "4!");
        z0 = a("token_type_prefixes_arj", "json_v3!");
        A0 = a("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
        B0 = a("axon_events", O0000000000.Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww(",", new CharSequence[]{"page_view", FirebaseAnalytics.Event.VIEW_ITEM, FirebaseAnalytics.Event.ADD_TO_CART, FirebaseAnalytics.Event.BEGIN_CHECKOUT, FirebaseAnalytics.Event.PURCHASE, FirebaseAnalytics.Event.ADD_PAYMENT_INFO, FirebaseAnalytics.Event.GENERATE_LEAD, "login", FirebaseAnalytics.Event.SIGN_UP, "search", "subscribe", FirebaseAnalytics.Event.REMOVE_FROM_CART}));
        TimeUnit timeUnit2 = TimeUnit.DAYS;
        C0 = a("cache_file_ttl_seconds", Long.valueOf(timeUnit2.toSeconds(1L)));
        D0 = a("cache_max_size_mb", -1);
        E0 = a("precache_delimiters", ")]', ");
        F0 = a("ad_resource_caching_enabled", bool2);
        G0 = a("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
        H0 = a("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
        I0 = a("resource_max_filename_length", 255);
        J0 = a("dfirf", bool);
        K0 = a("dfipf", bool);
        L0 = a("dcrome", bool);
        M0 = a("dcrobs", bool);
        N0 = a("pcro", bool);
        O0 = a("serfaad", bool);
        P0 = a("mdafra", 1);
        Q0 = a("ssch", bool2);
        R0 = a("suaf", bool);
        S0 = a("lfblrs", bool);
        T0 = a("ape", bool);
        U0 = a("pafqi", bool);
        TimeUnit timeUnit3 = TimeUnit.MINUTES;
        V0 = a("pae_ms", Long.valueOf(timeUnit3.toMillis(5L)));
        W0 = a("pamttl_ms", Long.valueOf(timeUnit.toMillis(5L)));
        X0 = a("saewib", bool);
        Y0 = a("fsae_ms", -1L);
        Z0 = a("raae", bool);
        a1 = a("vr_retry_count_v1", 1);
        b1 = a("cr_retry_count_v1", 1);
        c1 = a("text_incent_warning_title", "Attention!");
        d1 = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
        e1 = a("text_incent_warning_close_option", "Close");
        f1 = a("text_incent_warning_continue_option", "Keep Watching");
        g1 = a("close_button_touch_area", 0);
        h1 = a("close_button_outside_touch_area", 0);
        i1 = a("creative_debugger_enabled", bool2);
        j1 = a("smdfhcdb", bool2);
        k1 = a("use_background_view_for_ad_clicks", bool2);
        l1 = a("viewability_adview_imp_delay_ms", Long.valueOf(timeUnit.toMillis(1L)));
        m1 = a("viewability_adview_banner_min_width", Integer.valueOf((int) Sdk.SDKError.Reason.WEBVIEW_ERROR_VALUE));
        n1 = a("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
        MaxAdFormat maxAdFormat = MaxAdFormat.MREC;
        o1 = a("viewability_adview_mrec_min_width", Integer.valueOf(maxAdFormat.getSize().getWidth()));
        p1 = a("viewability_adview_mrec_min_height", Integer.valueOf(maxAdFormat.getSize().getHeight()));
        q1 = a("viewability_adview_leader_min_width", 728);
        r1 = a("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
        s1 = a("viewability_adview_native_min_width", 0);
        t1 = a("viewability_adview_native_min_height", 0);
        u1 = a("viewability_adview_min_alpha", Float.valueOf(10.0f));
        v1 = a("viewability_timer_min_visible_ms", Long.valueOf(timeUnit.toMillis(1L)));
        w1 = a("viewability_timer_interval_ms", 100L);
        x1 = a("expandable_close_button_size", 27);
        y1 = a("expandable_h_close_button_margin", 10);
        z1 = a("expandable_t_close_button_margin", 10);
        A1 = a("expandable_lhs_close_button", bool);
        B1 = a("expandable_close_button_touch_area", 0);
        C1 = a("forward_lifecycle_events_to_adview_webview", bool);
        D1 = a("forward_in_app_browser_events_to_adview_webview", bool);
        E1 = a("forward_external_redirect_events_to_adview_webview", bool);
        F1 = a("forward_preload_events_to_adview_webview", bool);
        G1 = a("iaad", bool);
        H1 = a("fullscreen_ad_pending_display_state_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        I1 = a("fullscreen_ad_showing_state_timeout_ms", Long.valueOf(timeUnit3.toMillis(2L)));
        J1 = a("lhs_close_button_video", bool);
        K1 = a("close_button_right_margin_video", 4);
        L1 = a("close_button_size_video", 30);
        M1 = a("close_button_top_margin_video", 8);
        N1 = a("video_countdown_clock_margin", 10);
        O1 = a("video_countdown_clock_gravity", 83);
        P1 = a("countdown_clock_size", 32);
        Q1 = a("countdown_clock_stroke_size", 4);
        R1 = a("countdown_clock_text_size", 28);
        S1 = a("draw_countdown_clock", bool2);
        T1 = a("inter_display_delay", 200L);
        U1 = a("maximum_close_button_delay_seconds", 999L);
        V1 = a("respect_close_button", bool2);
        W1 = a("lhs_skip_button", bool2);
        X1 = a("track_app_killed", bool);
        Y1 = a("track_ad_duration", bool);
        Z1 = a("track_ad_duration_interval_ms", Long.valueOf(timeUnit.toMillis(1L)));
        a2 = a("simplified_app_killed_detection", bool);
        b2 = a("app_closed_time_threshold_for_app_killed_event_ms", Long.valueOf(timeUnit.toMillis(60L)));
        c2 = a("mute_controls_enabled", bool);
        d2 = a("allow_user_muting", bool2);
        e2 = a("mute_videos", bool);
        f2 = a("show_mute_by_default", bool);
        g2 = a("mute_with_user_settings", bool2);
        h2 = a("mute_button_size", 32);
        i2 = a("mute_button_margin", 10);
        j2 = a("mute_button_gravity", 85);
        k2 = a("progress_bar_step", 25L);
        l2 = a("progress_bar_scale", 10000);
        m2 = a("progress_bar_vertical_padding", -8);
        n2 = a("vs_buffer_indicator_size", 50);
        o2 = a("video_zero_length_as_computed", bool);
        p2 = a("set_poststitial_muted_initial_delay_ms", 500L);
        q2 = a("fasuic", bool2);
        r2 = a("fsahrpg", bool2);
        s2 = a("eaafrwsoa", bool2);
        t2 = a("postitial_progress_bar_step_ms", 25L);
        u2 = a("postitial_progress_bar_on_bottom", bool2);
        v2 = a("postitial_progress_bar_vertical_padding", -8);
        w2 = a("postitial_progress_bar_scale", 10000);
        x2 = a("fahosu", bool);
        y2 = a("system_insets_mask", Integer.valueOf(z6.f()));
        z2 = a("nsuttcl", bool);
        A2 = a("submit_postback_timeout", Integer.valueOf((int) timeUnit.toMillis(10L)));
        B2 = a("submit_postback_retries", 4);
        C2 = a("max_postback_attempts", 3);
        D2 = a("max_persisted_postbacks", 100);
        E2 = a("submit_web_tracker_timeout", Integer.valueOf((int) timeUnit.toMillis(7L)));
        F2 = a("sossp", bool);
        G2 = a("spp", bool2);
        H2 = a("fire_native_ad_postbacks_from_webview", bool);
        I2 = a("use_requests_for_native_ad_click_postbacks", bool);
        J2 = a("preload_postback_webview", bool);
        K2 = a("get_retry_delay_v1", Integer.valueOf((int) timeUnit.toMillis(10L)));
        L2 = a("http_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        M2 = a("http_socket_timeout", Integer.valueOf((int) timeUnit.toMillis(20L)));
        N2 = a("fetch_ad_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        O2 = a("fetch_ad_retry_count_v1", 1);
        P2 = a("faer", bool);
        Q2 = a("faroae", bool);
        R2 = a("submit_data_retry_count_v1", 1);
        S2 = a("response_buffer_size", 16000);
        T2 = a("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) timeUnit.toMillis(10L)));
        U2 = a("fetch_basic_settings_retry_count", 3);
        V2 = a("fetch_basic_settings_on_reconnect", bool);
        W2 = a("skip_fetch_basic_settings_if_not_connected", bool);
        X2 = a("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) timeUnit.toMillis(2L)));
        Y2 = a("idflrwbe", bool);
        Z2 = a("falawpr", bool);
        a3 = a("sort_query_parameters", bool);
        b3 = a("communicator_request_timeout_ms", Long.valueOf(timeUnit.toMillis(10L)));
        c3 = a("communicator_request_retry_count", 3);
        d3 = a("communicator_request_retry_delay_ms", Long.valueOf(timeUnit.toMillis(2L)));
        e3 = a("rfbsd_ms", -1L);
        f3 = a("ehkpd_ms", 500L);
        g3 = a("rironc", bool);
        h3 = a("rroncbd", bool);
        i3 = a("wverc_ms", Long.valueOf(timeUnit.toMillis(5L)));
        j3 = a("sducifm", bool);
        k3 = a("session_tracking_cooldown_on_event_fire", bool2);
        l3 = a("session_tracking_resumed_cooldown_minutes", 90L);
        m3 = a("session_tracking_paused_cooldown_minutes", 90L);
        n3 = a("qq", bool);
        o3 = a("qq1", bool2);
        p3 = a("qq2", bool2);
        q3 = a("qq3", bool2);
        r3 = a("qq4", bool2);
        s3 = a("qq5", bool2);
        t3 = a("qq6", bool2);
        u3 = a("qq7", bool2);
        v3 = a("qq8", bool2);
        w3 = a("qq9", bool);
        x3 = a("qq10", bool2);
        y3 = a("qq11", bool2);
        z3 = a("qq12", bool2);
        A3 = a("pui", bool2);
        B3 = a("plugin_version", "");
        C3 = a("validate_admob_adapter_sdk_version", bool2);
        D3 = a("ccbtbsic", bool);
        E3 = a("hgn", bool2);
        F3 = a("cso", bool2);
        G3 = a("cfs", bool2);
        H3 = a("cmi", bool2);
        I3 = a("crat", bool2);
        J3 = a("cvs", bool2);
        K3 = a("caf", bool2);
        L3 = a("cf", bool2);
        M3 = a("cmtl", bool2);
        N3 = a("cnr", bool2);
        O3 = a("ccr", bool);
        P3 = a("adr", bool2);
        Q3 = a("volume_normalization_factor", Float.valueOf(100.0f));
        R3 = a("system_user_agent_collection_enabled", bool);
        S3 = a("user_agent_collection_enabled", bool);
        T3 = a("use_cached_user_agent_as_default", bool2);
        U3 = a("collect_device_angle", bool2);
        V3 = a("collect_device_movement", bool2);
        W3 = a("movement_degradation", Float.valueOf(0.75f));
        X3 = a("device_sensor_period_ms", 250);
        Y3 = a("mps", "");
        Z3 = a("mpsl", 3);
        a4 = a("mpis", "com.applovin,dalvik,java,android,com.android");
        b4 = a("cmps", bool);
        c4 = a("rmps", bool);
        d4 = a("collect_webview_package_info", bool);
        e4 = a("webview_package_names", "com.google.android.webview,com.android.webview");
        f4 = a("collect_opengl_version", bool);
        g4 = a("ncre", bool);
        h4 = a("ncrs", "4,5,6,7,8,11,16");
        i4 = a("ncrcs", bool);
        j4 = a("ncrcai", bool2);
        k4 = a("tmas", "");
        l4 = a("cin_v2", bool);
        m4 = a("suia", bool2);
        n4 = a("umsm", bool);
        o4 = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        p4 = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        q4 = a("vast_max_response_length", 640000);
        r4 = a("vast_max_wrapper_depth", 5);
        s4 = a("vast_unsupported_video_extensions", "ogv,flv");
        t4 = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        u4 = a("vast_validate_with_extension_if_no_video_type", bool2);
        v4 = a("vast_wrapper_resolution_retry_count_v1", 1);
        w4 = a("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) timeUnit.toMillis(30L)));
        x4 = a("vast_industry_icon_max_size", 20);
        y4 = a("vast_industry_icon_margin", 12);
        z4 = a("vast_industry_icon_gravity", 85);
        A4 = a("vast_native_mute_button_size", 24);
        B4 = a("vast_native_play_pause_button_size", 24);
        C4 = a("vast_native_video_widget_padding", 6);
        D4 = a("vast_native_video_widget_alpha", Float.valueOf(0.5f));
        E4 = a("vast_native_video_widgets_enabled", bool2);
        F4 = a("vast_replay_video_upon_completion", bool2);
        G4 = a("vast_replay_icon_size", 64);
        H4 = a("vcjfhr", bool);
        I4 = a("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
        J4 = a("vpenfxr", "(<Error><!\\[CDATA\\[[^>]*><\\/Error>)");
        K4 = a("vast_fire_trackers_from_webview", bool);
        L4 = a("ree", bool2);
        i4.a aVar = i4.a.DEFAULT;
        M4 = a("ree_t", Integer.valueOf(aVar.b()));
        N4 = a("btee", bool2);
        O4 = a("btet", Integer.valueOf(aVar.b()));
        P4 = a("reetoa", bool);
        Q4 = a("reet_msfs", Integer.valueOf(aVar.b()));
        R4 = a("reet_msma", Integer.valueOf(i4.a.V2.b()));
        S4 = a("reet_msmd", Integer.valueOf(aVar.b()));
        T4 = a("reet_asfp", Integer.valueOf(aVar.b()));
        U4 = a("reet_asfg", Integer.valueOf(aVar.b()));
        V4 = a("reet_aset", Integer.valueOf(aVar.b()));
        W4 = a("reet_esdi", Integer.valueOf(aVar.b()));
        X4 = a("reet_esrp", Integer.valueOf(aVar.b()));
        Y4 = a("apdra", bool);
        Z4 = a("apdrfs", bool);
        a5 = a("apdrma", bool);
        b5 = a("apdrmd", bool);
        c5 = a("apdrfa", bool);
        d5 = a("apdrev", bool);
        e5 = a("apdrdi", bool);
        f5 = a("apdrrp", bool);
        g5 = a("server_timestamp_ms", 0L);
        h5 = a("device_timestamp_ms", 0L);
        i5 = a("gzip_min_length", 0);
        j5 = a("gzip_encoding_default", bool);
        k5 = a("fetch_settings_gzip", bool);
        l5 = a("device_init_gzip", bool);
        m5 = a("fetch_ad_gzip", bool);
        n5 = a("event_tracking_gzip", bool);
        o5 = a("reward_postback_gzip", bool);
        p5 = a("handle_render_process_gone", bool2);
        q5 = a("rworpg", bool2);
        r5 = a("fdadaomr", bool2);
        s5 = a("vfswccar", bool);
        t5 = a("sparafad", bool);
        u5 = a("fahctdmr", bool);
        v5 = a("teorpc", bool);
        w5 = a("set_webview_render_process_client", bool);
        x5 = a("disable_webview_hardware_acceleration", bool);
        y5 = a("anr_detection_enabled", bool);
        z5 = a("anr_trigger_millis", 4000L);
        A5 = a("anr_touch_millis", Long.valueOf((long) C.DEFAULT_MAX_SEEK_TO_PREVIOUS_POSITION_MS));
        B5 = a("anr_check_millis", Long.valueOf((long) C.DEFAULT_MAX_SEEK_TO_PREVIOUS_POSITION_MS));
        C5 = a("spadib", bool);
        D5 = a("uobid", bool2);
        E5 = a("bvde", bool);
        F5 = a("bvdidm", 1000L);
        G5 = a("bvdim", 4000L);
        H5 = a("bvdrs", 10);
        I5 = a("bvdct", 230);
        J5 = a("bvdict", 3);
        K5 = a("bvad", bool);
        L5 = a("bvebb", bool2);
        M5 = a("bvscb", bool2);
        N5 = a("bvlmtb", -1L);
        O5 = a("bvsafw", bool2);
        P5 = a("aocve", bool);
        Q5 = a("dwvvb", bool);
        R5 = a("stcpc", bool);
        S5 = a("stcic", bool2);
        T5 = a("qjscwwvl", bool);
        U5 = a("web_contents_debugging_enabled", bool);
        V5 = a("fcioiauiidb", bool2);
        W5 = a("teouauiidb", bool2);
        X5 = a("usc", bool);
        Y5 = a("should_apply_web_view_settings_to_web_view_button", bool);
        Z5 = a("should_use_cached_screen_size_for_foldable_devices", bool2);
        a6 = a("should_persist_shared_prefs_with_background_commit", bool);
        b6 = a("wvmldt", -1);
        c6 = a("fmldt", -1);
        d6 = a("csl", -1);
        e6 = a("should_use_applovin_adaptive_sizing_formula", bool);
        f6 = a("cdbpn", bool);
        g6 = a("cavdi", bool);
        h6 = a("pvdiaqp", bool);
        i6 = a("sudbia", bool);
        j6 = a("pbpn", "");
        k6 = a("nvelifapd", bool);
        l6 = a("sufecfhrd", bool);
        m6 = a("ignored_auto_redirect_schemes", O0000000000.Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww(",", new CharSequence[]{"about", "data", "file"}));
        n6 = a("config_consent_dialog_state", "unknown");
        o6 = a("country_code", "");
        p6 = a("approved_installers_for_package_name_override", "com.google.android.packageinstaller");
        q6 = a("consent_flow_doc_url", "https://developers.applovin.com/en/android/overview/terms-and-privacy-policy-flow");
        r6 = a("consent_flow_unity_doc_url", "https://developers.applovin.com/en/unity/overview/terms-and-privacy-policy-flow");
        s6 = a("cfadtml", 20);
        t6 = a("cfgcsmrc", -1);
        u6 = a("cfgcsrec", String.valueOf(3));
        v6 = a("enable_custom_tabs_service", bool2);
        w6 = a("custom_tabs_chrome_package_names", "com.android.chrome");
        x6 = a("custom_tabs_prefer_default_browser", bool2);
        y6 = a("custom_tabs_animation_enabled", bool2);
        z6 = a("ps_etr", bool);
        A6 = a("ps_tri_ms", Long.valueOf(timeUnit2.toMillis(7L)));
        B6 = a("ps_ftri_ms", -1L);
        C6 = a("ps_sroftr", bool);
        D6 = a("ps_sroftrof", bool);
        E6 = a("gawvbu", "https://applovin.com");
        F6 = a("c_sticky_topics", "safedk_init,user_info");
        G6 = a("communicator_enabled", bool2);
        H6 = a("adse", bool2);
    }

    public l4(String str, Object obj) {
        if (str != null) {
            if (obj != null) {
                this.f3179a = str;
                this.b = obj;
                return;
            }
            throw new IllegalArgumentException("No default value specified");
        }
        throw new IllegalArgumentException("No name specified");
    }

    public static Collection c() {
        return Collections.synchronizedCollection(d.values());
    }

    public Object a() {
        return this.b;
    }

    public String b() {
        return this.f3179a;
    }

    @Override // java.lang.Comparable
    public int compareTo(Object obj) {
        if (obj instanceof l4) {
            return this.f3179a.compareTo(((l4) obj).b());
        }
        return 0;
    }

    public Object a(Object obj) {
        return this.b.getClass().cast(obj);
    }

    public static l4 a(String str, Object obj) {
        if (obj != null) {
            if (c.contains(obj.getClass())) {
                l4 l4Var = new l4(str, obj);
                Map map = d;
                if (!map.containsKey(str)) {
                    map.put(str, l4Var);
                    return l4Var;
                }
                throw new IllegalArgumentException("Setting has already been used: " + str);
            }
            throw new IllegalArgumentException("Unsupported value type: " + obj.getClass());
        }
        throw new IllegalArgumentException("No default value specified");
    }

    public static l4 a(String str) {
        return (l4) d.get(str);
    }
}
