package com.tencent.liteav.videobase.videobase;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.media3.common.PlaybackException;
import com.google.android.gms.auth.api.proxy.AuthApiStatusCodes;
/* compiled from: Proguard */
/* loaded from: classes6.dex */
public enum f {
    STATUS_VIDEO_NONE(0),
    STATUS_VIDEO_CAPTURE_REAL_FRAME_RATE(1),
    STATUS_VIDEO_PREPROCESS_AVERAGE_PROCESS_COST(101),
    STATUS_VIDEO_PREPROCESS_FPS_IN(103),
    STATUS_VIDEO_ENCODE_REAL_ENCODE_BITRATE(201),
    STATUS_VIDEO_ENCODE_REAL_FRAME_RATE(202),
    STATUS_VIDEO_ENCODE_AVERAGE_ENCODE_COST(203),
    STATUS_VIDEO_SW_DECODE_TASK_COST(404),
    STATUS_VIDEO_HW_DECODE_TASK_COST(405),
    STATUS_VIDEO_RENDER_RESOLUTION(502),
    STATUS_VIDEO_CONSUMER_RECEIVE_FPS(TypedValues.TransitionType.TYPE_DURATION),
    STATUS_VIDEO_DECODER_FRAMERATE(804),
    STATUS_VIDEO_DECODER_ERROR(805),
    STATUS_VIDEO_CAPTURE_FRAME(1000),
    STATUS_VIDEO_INCOME_FRAME(1001),
    STATUS_VIDEO_CAMERA_START_COST(1002),
    STATUS_VIDEO_CAMERA_START_ERROR_TYPE(1003),
    STATUS_VIDEO_PREPROCESS_TIME(2000),
    STATUS_VIDEO_PREPROCESS_BEAUTY_SETTINGS(2001),
    STATUS_VIDEO_CUSTOM_PREPROCESS_AVERAGE_COST(2002),
    STATUS_VIDEO_ENCODER_TYPE(3000),
    STATUS_VIDEO_ENCODER_FRAME(3001),
    STATUS_VIDEO_ENCODER_COST(3004),
    STATUS_VIDEO_ENCODER_CODEC(3005),
    STATUS_VIDEO_ENCODER_ABILITY(AuthApiStatusCodes.AUTH_APP_CERT_ERROR),
    STATUS_VIDEO_HW_ENCODE_START_ERROR_TYPE(3007),
    STATUS_VIDEO_ENCODE_TASK_COST(3008),
    STATUS_VIDEO_DECODER_TYPE(4000),
    STATUS_VIDEO_DECODER_FRAME(PlaybackException.ERROR_CODE_DECODER_INIT_FAILED),
    STATUS_VIDEO_DECODER_COST(PlaybackException.ERROR_CODE_DECODING_FORMAT_EXCEEDS_CAPABILITIES),
    STATUS_VIDEO_DECODER_CACHE(PlaybackException.ERROR_CODE_DECODING_FORMAT_UNSUPPORTED),
    STATUS_VIDEO_DECODER_CODEC(PlaybackException.ERROR_CODE_DECODING_RESOURCES_RECLAIMED),
    STATUS_VIDEO_DECODER_CODEC_COST(4007),
    STATUS_VIDEO_HW_DECODE_START_ERROR_TYPE(4008),
    STATUS_VIDEO_DECODE_TASK_COST(4009),
    STATUS_VIDEO_RENDER_FRAME(5000),
    STATUS_VIDEO_RECEIVED_FRAME(PlaybackException.ERROR_CODE_DRM_UNSPECIFIED),
    STATUS_VIDEO_DROP_FRAME(6001),
    STATUS_CONSUMER_FINISH_HANDLE_FRAME(6002);
    
    private static final f[] N = values();
    private final int value;

    f(int i) {
        this.value = i;
    }
}
