package com.vungle.ads.internal.model;

import androidx.core.view.accessibility.AccessibilityEventCompat;
import androidx.media3.common.C;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.mbridge.msdk.foundation.entity.CampaignEx;
import com.tencent.thumbplayer.tcmedia.core.common.TPMediaCodecProfileLevel;
import com.vungle.ads.internal.Constants;
import com.vungle.ads.internal.model.AdPayload;
import java.util.List;
import java.util.Map;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Metadata;
import kotlin.ReplaceWith;
import kotlin.Unit;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.ArrayListSerializer;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import kotlinx.serialization.internal.StringSerializer;
import org.jetbrains.annotations.NotNull;
/* compiled from: Proguard */
@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"com/vungle/ads/internal/model/AdPayload.AdUnit.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lcom/vungle/ads/internal/model/AdPayload$AdUnit;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "vungle-ads_release"}, k = 1, mv = {1, 7, 1}, xi = 48)
@Deprecated(level = DeprecationLevel.HIDDEN, message = "This synthesized declaration should not be used directly", replaceWith = @ReplaceWith(expression = "", imports = {}))
/* loaded from: classes6.dex */
public final class AdPayload$AdUnit$$serializer implements GeneratedSerializer<AdPayload.AdUnit> {
    @NotNull
    public static final AdPayload$AdUnit$$serializer INSTANCE;
    public static final /* synthetic */ SerialDescriptor descriptor;

    static {
        AdPayload$AdUnit$$serializer adPayload$AdUnit$$serializer = new AdPayload$AdUnit$$serializer();
        INSTANCE = adPayload$AdUnit$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("com.vungle.ads.internal.model.AdPayload.AdUnit", adPayload$AdUnit$$serializer, 29);
        pluginGeneratedSerialDescriptor.addElement("id", true);
        pluginGeneratedSerialDescriptor.addElement("ad_type", true);
        pluginGeneratedSerialDescriptor.addElement(FirebaseAnalytics.Param.AD_SOURCE, true);
        pluginGeneratedSerialDescriptor.addElement("expiry", true);
        pluginGeneratedSerialDescriptor.addElement("deeplink_url", true);
        pluginGeneratedSerialDescriptor.addElement("click_coordinates_enabled", true);
        pluginGeneratedSerialDescriptor.addElement("ad_load_optimization", true);
        pluginGeneratedSerialDescriptor.addElement("template_heartbeat_check", true);
        pluginGeneratedSerialDescriptor.addElement("mediation_name", true);
        pluginGeneratedSerialDescriptor.addElement("info", true);
        pluginGeneratedSerialDescriptor.addElement("sleep", true);
        pluginGeneratedSerialDescriptor.addElement("error_code", true);
        pluginGeneratedSerialDescriptor.addElement("tpat", true);
        pluginGeneratedSerialDescriptor.addElement("vm_url", true);
        pluginGeneratedSerialDescriptor.addElement("vm_version", true);
        pluginGeneratedSerialDescriptor.addElement("ad_market_id", true);
        pluginGeneratedSerialDescriptor.addElement("notification", true);
        pluginGeneratedSerialDescriptor.addElement(Constants.LOAD_AD, true);
        pluginGeneratedSerialDescriptor.addElement("viewability", true);
        pluginGeneratedSerialDescriptor.addElement("template_url", true);
        pluginGeneratedSerialDescriptor.addElement("template_type", true);
        pluginGeneratedSerialDescriptor.addElement("template_settings", true);
        pluginGeneratedSerialDescriptor.addElement(CampaignEx.JSON_KEY_CREATIVE_ID, true);
        pluginGeneratedSerialDescriptor.addElement("app_id", true);
        pluginGeneratedSerialDescriptor.addElement("show_close", true);
        pluginGeneratedSerialDescriptor.addElement("show_close_incentivized", true);
        pluginGeneratedSerialDescriptor.addElement("ad_size", true);
        pluginGeneratedSerialDescriptor.addElement("cacheable_assets_required", true);
        pluginGeneratedSerialDescriptor.addElement("webview_settings", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private AdPayload$AdUnit$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] childSerializers() {
        StringSerializer stringSerializer = StringSerializer.INSTANCE;
        KSerializer<?> nullable = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer<?> nullable2 = BuiltinSerializersKt.getNullable(stringSerializer);
        KSerializer<?> nullable3 = BuiltinSerializersKt.getNullable(stringSerializer);
        IntSerializer intSerializer = IntSerializer.INSTANCE;
        KSerializer<?> nullable4 = BuiltinSerializersKt.getNullable(intSerializer);
        KSerializer<?> nullable5 = BuiltinSerializersKt.getNullable(stringSerializer);
        BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
        return new KSerializer[]{nullable, nullable2, nullable3, nullable4, nullable5, BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(AdPayload.TpatSerializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(new ArrayListSerializer(stringSerializer)), BuiltinSerializersKt.getNullable(new ArrayListSerializer(stringSerializer)), BuiltinSerializersKt.getNullable(AdPayload$ViewAbility$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(AdPayload$TemplateSettings$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(stringSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(intSerializer), BuiltinSerializersKt.getNullable(AdPayload$AdSizeInfo$$serializer.INSTANCE), BuiltinSerializersKt.getNullable(booleanSerializer), BuiltinSerializersKt.getNullable(AdPayload$WebViewSettings$$serializer.INSTANCE)};
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public AdPayload.AdUnit deserialize(@NotNull Decoder decoder) {
        Integer num;
        String str;
        List list;
        String str2;
        AdPayload.TemplateSettings templateSettings;
        Boolean bool;
        String str3;
        int i;
        Integer num2;
        Object obj;
        String str4;
        Object obj2;
        Object obj3;
        Object obj4;
        Object obj5;
        String str5;
        AdPayload.AdSizeInfo adSizeInfo;
        Integer num3;
        String str6;
        String str7;
        AdPayload.ViewAbility viewAbility;
        List list2;
        String str8;
        String str9;
        Object obj6;
        Object obj7;
        Map map;
        AdPayload.WebViewSettings webViewSettings;
        Object obj8;
        String str10;
        Object obj9;
        AdPayload.WebViewSettings webViewSettings2;
        String str11;
        Map map2;
        String str12;
        String str13;
        String str14;
        Object obj10;
        List list3;
        AdPayload.ViewAbility viewAbility2;
        String str15;
        String str16;
        String str17;
        Object obj11;
        Integer num4;
        AdPayload.AdSizeInfo adSizeInfo2;
        Boolean bool2;
        AdPayload.TemplateSettings templateSettings2;
        Map map3;
        List list4;
        String str18;
        Map map4;
        List list5;
        String str19;
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeDecoder beginStructure = decoder.beginStructure(descriptor2);
        if (beginStructure.decodeSequentially()) {
            StringSerializer stringSerializer = StringSerializer.INSTANCE;
            Object decodeNullableSerializableElement = beginStructure.decodeNullableSerializableElement(descriptor2, 0, stringSerializer, null);
            Object decodeNullableSerializableElement2 = beginStructure.decodeNullableSerializableElement(descriptor2, 1, stringSerializer, null);
            obj7 = beginStructure.decodeNullableSerializableElement(descriptor2, 2, stringSerializer, null);
            IntSerializer intSerializer = IntSerializer.INSTANCE;
            obj6 = beginStructure.decodeNullableSerializableElement(descriptor2, 3, intSerializer, null);
            obj5 = beginStructure.decodeNullableSerializableElement(descriptor2, 4, stringSerializer, null);
            BooleanSerializer booleanSerializer = BooleanSerializer.INSTANCE;
            obj3 = beginStructure.decodeNullableSerializableElement(descriptor2, 5, booleanSerializer, null);
            obj4 = beginStructure.decodeNullableSerializableElement(descriptor2, 6, booleanSerializer, null);
            obj2 = beginStructure.decodeNullableSerializableElement(descriptor2, 7, booleanSerializer, null);
            Object decodeNullableSerializableElement3 = beginStructure.decodeNullableSerializableElement(descriptor2, 8, stringSerializer, null);
            obj = beginStructure.decodeNullableSerializableElement(descriptor2, 9, stringSerializer, null);
            Object decodeNullableSerializableElement4 = beginStructure.decodeNullableSerializableElement(descriptor2, 10, intSerializer, null);
            num2 = beginStructure.decodeNullableSerializableElement(descriptor2, 11, intSerializer, null);
            str3 = decodeNullableSerializableElement;
            Object decodeNullableSerializableElement5 = beginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, null);
            Object decodeNullableSerializableElement6 = beginStructure.decodeNullableSerializableElement(descriptor2, 13, stringSerializer, null);
            map = decodeNullableSerializableElement5;
            str9 = beginStructure.decodeNullableSerializableElement(descriptor2, 14, stringSerializer, null);
            str8 = beginStructure.decodeNullableSerializableElement(descriptor2, 15, stringSerializer, null);
            str = decodeNullableSerializableElement6;
            list2 = beginStructure.decodeNullableSerializableElement(descriptor2, 16, new ArrayListSerializer(stringSerializer), null);
            Object decodeNullableSerializableElement7 = beginStructure.decodeNullableSerializableElement(descriptor2, 17, new ArrayListSerializer(stringSerializer), null);
            Object decodeNullableSerializableElement8 = beginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, null);
            Object decodeNullableSerializableElement9 = beginStructure.decodeNullableSerializableElement(descriptor2, 19, stringSerializer, null);
            viewAbility = decodeNullableSerializableElement8;
            Object decodeNullableSerializableElement10 = beginStructure.decodeNullableSerializableElement(descriptor2, 20, stringSerializer, null);
            str2 = decodeNullableSerializableElement9;
            Object decodeNullableSerializableElement11 = beginStructure.decodeNullableSerializableElement(descriptor2, 21, AdPayload$TemplateSettings$$serializer.INSTANCE, null);
            Object decodeNullableSerializableElement12 = beginStructure.decodeNullableSerializableElement(descriptor2, 22, stringSerializer, null);
            Object decodeNullableSerializableElement13 = beginStructure.decodeNullableSerializableElement(descriptor2, 23, stringSerializer, null);
            obj8 = beginStructure.decodeNullableSerializableElement(descriptor2, 24, intSerializer, null);
            str6 = decodeNullableSerializableElement13;
            num3 = beginStructure.decodeNullableSerializableElement(descriptor2, 25, intSerializer, null);
            Object decodeNullableSerializableElement14 = beginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$AdSizeInfo$$serializer.INSTANCE, null);
            str10 = decodeNullableSerializableElement12;
            i = 536870911;
            bool = beginStructure.decodeNullableSerializableElement(descriptor2, 27, booleanSerializer, null);
            str4 = decodeNullableSerializableElement3;
            templateSettings = decodeNullableSerializableElement11;
            list = decodeNullableSerializableElement7;
            num = decodeNullableSerializableElement4;
            adSizeInfo = decodeNullableSerializableElement14;
            webViewSettings = beginStructure.decodeNullableSerializableElement(descriptor2, 28, AdPayload$WebViewSettings$$serializer.INSTANCE, null);
            str5 = decodeNullableSerializableElement2;
            str7 = decodeNullableSerializableElement10;
        } else {
            boolean z = true;
            Object obj12 = null;
            AdPayload.WebViewSettings webViewSettings3 = null;
            Integer num5 = null;
            Object obj13 = null;
            String str20 = null;
            String str21 = null;
            Object obj14 = null;
            Object obj15 = null;
            Object obj16 = null;
            num = null;
            Object obj17 = null;
            Map map5 = null;
            String str22 = null;
            String str23 = null;
            String str24 = null;
            List list6 = null;
            List list7 = null;
            AdPayload.ViewAbility viewAbility3 = null;
            String str25 = null;
            String str26 = null;
            AdPayload.TemplateSettings templateSettings3 = null;
            String str27 = null;
            String str28 = null;
            Object obj18 = null;
            Integer num6 = null;
            AdPayload.AdSizeInfo adSizeInfo3 = null;
            Boolean bool3 = null;
            String str29 = null;
            int i2 = 0;
            Object obj19 = null;
            while (z) {
                int decodeElementIndex = beginStructure.decodeElementIndex(descriptor2);
                switch (decodeElementIndex) {
                    case -1:
                        obj9 = obj12;
                        webViewSettings2 = webViewSettings3;
                        str11 = str21;
                        map2 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list3 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Unit unit = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        z = false;
                        map3 = map2;
                        str21 = str11;
                        obj12 = obj9;
                        list4 = list3;
                        list6 = obj10;
                        break;
                    case 0:
                        obj9 = obj12;
                        webViewSettings2 = webViewSettings3;
                        String str30 = str21;
                        map2 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list3 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str11 = str30;
                        Object decodeNullableSerializableElement15 = beginStructure.decodeNullableSerializableElement(descriptor2, 0, StringSerializer.INSTANCE, str29);
                        i2 |= 1;
                        Unit unit2 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str29 = decodeNullableSerializableElement15;
                        map3 = map2;
                        str21 = str11;
                        obj12 = obj9;
                        list4 = list3;
                        list6 = obj10;
                        break;
                    case 1:
                        webViewSettings2 = webViewSettings3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object obj20 = obj12;
                        Object decodeNullableSerializableElement16 = beginStructure.decodeNullableSerializableElement(descriptor2, 1, StringSerializer.INSTANCE, str21);
                        i2 |= 2;
                        Unit unit3 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        map3 = map5;
                        list4 = list7;
                        str21 = decodeNullableSerializableElement16;
                        list6 = list6;
                        obj12 = obj20;
                        break;
                    case 2:
                        webViewSettings2 = webViewSettings3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement17 = beginStructure.decodeNullableSerializableElement(descriptor2, 2, StringSerializer.INSTANCE, obj19);
                        i2 |= 4;
                        Unit unit4 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj19 = decodeNullableSerializableElement17;
                        map3 = map5;
                        list4 = list7;
                        str21 = str21;
                        list6 = obj10;
                        break;
                    case 3:
                        webViewSettings2 = webViewSettings3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        obj12 = beginStructure.decodeNullableSerializableElement(descriptor2, 3, IntSerializer.INSTANCE, obj12);
                        i2 |= 8;
                        Unit unit5 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        map3 = map5;
                        list4 = list7;
                        str21 = str21;
                        list6 = obj10;
                        break;
                    case 4:
                        webViewSettings2 = webViewSettings3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement18 = beginStructure.decodeNullableSerializableElement(descriptor2, 4, StringSerializer.INSTANCE, obj17);
                        i2 |= 16;
                        Unit unit6 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj17 = decodeNullableSerializableElement18;
                        map3 = map5;
                        list4 = list7;
                        str21 = str21;
                        list6 = obj10;
                        break;
                    case 5:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement19 = beginStructure.decodeNullableSerializableElement(descriptor2, 5, BooleanSerializer.INSTANCE, obj15);
                        i2 |= 32;
                        Unit unit7 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj15 = decodeNullableSerializableElement19;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 6:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement20 = beginStructure.decodeNullableSerializableElement(descriptor2, 6, BooleanSerializer.INSTANCE, obj16);
                        i2 |= 64;
                        Unit unit8 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj16 = decodeNullableSerializableElement20;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 7:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement21 = beginStructure.decodeNullableSerializableElement(descriptor2, 7, BooleanSerializer.INSTANCE, obj14);
                        i2 |= 128;
                        Unit unit9 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj14 = decodeNullableSerializableElement21;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 8:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement22 = beginStructure.decodeNullableSerializableElement(descriptor2, 8, StringSerializer.INSTANCE, str20);
                        i2 |= 256;
                        Unit unit10 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str20 = decodeNullableSerializableElement22;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 9:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement23 = beginStructure.decodeNullableSerializableElement(descriptor2, 9, StringSerializer.INSTANCE, obj13);
                        i2 |= 512;
                        Unit unit11 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        obj13 = decodeNullableSerializableElement23;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 10:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement24 = beginStructure.decodeNullableSerializableElement(descriptor2, 10, IntSerializer.INSTANCE, num);
                        i2 |= 1024;
                        Unit unit12 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        num = decodeNullableSerializableElement24;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 11:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        map4 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement25 = beginStructure.decodeNullableSerializableElement(descriptor2, 11, IntSerializer.INSTANCE, num5);
                        i2 |= 2048;
                        Unit unit13 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        num5 = decodeNullableSerializableElement25;
                        map3 = map4;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 12:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        str13 = str23;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str12 = str22;
                        map3 = beginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, map5);
                        i2 |= 4096;
                        Unit unit14 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 13:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        str14 = str24;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str13 = str23;
                        Object decodeNullableSerializableElement26 = beginStructure.decodeNullableSerializableElement(descriptor2, 13, StringSerializer.INSTANCE, str22);
                        i2 |= 8192;
                        Unit unit15 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str12 = decodeNullableSerializableElement26;
                        map3 = map5;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 14:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        obj10 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str14 = str24;
                        Object decodeNullableSerializableElement27 = beginStructure.decodeNullableSerializableElement(descriptor2, 14, StringSerializer.INSTANCE, str23);
                        i2 |= 16384;
                        Unit unit16 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str13 = decodeNullableSerializableElement27;
                        map3 = map5;
                        str12 = str22;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 15:
                        webViewSettings2 = webViewSettings3;
                        str18 = str21;
                        Object obj21 = list6;
                        list5 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        obj10 = obj21;
                        Object decodeNullableSerializableElement28 = beginStructure.decodeNullableSerializableElement(descriptor2, 15, StringSerializer.INSTANCE, str24);
                        i2 |= 32768;
                        Unit unit17 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str14 = decodeNullableSerializableElement28;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        list4 = list5;
                        str21 = str18;
                        list6 = obj10;
                        break;
                    case 16:
                        webViewSettings2 = webViewSettings3;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement29 = beginStructure.decodeNullableSerializableElement(descriptor2, 16, new ArrayListSerializer(StringSerializer.INSTANCE), list6);
                        i2 |= 65536;
                        Unit unit18 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        str21 = str21;
                        list6 = decodeNullableSerializableElement29;
                        map3 = map5;
                        break;
                    case 17:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        str15 = str25;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        viewAbility2 = viewAbility3;
                        Object decodeNullableSerializableElement30 = beginStructure.decodeNullableSerializableElement(descriptor2, 17, new ArrayListSerializer(StringSerializer.INSTANCE), list7);
                        i2 |= 131072;
                        Unit unit19 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        list4 = decodeNullableSerializableElement30;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        str21 = str19;
                        break;
                    case 18:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str15 = str25;
                        Object decodeNullableSerializableElement31 = beginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, viewAbility3);
                        i2 |= 262144;
                        Unit unit20 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        viewAbility2 = decodeNullableSerializableElement31;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        str21 = str19;
                        break;
                    case 19:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement32 = beginStructure.decodeNullableSerializableElement(descriptor2, 19, StringSerializer.INSTANCE, str25);
                        i2 |= 524288;
                        Unit unit21 = Unit.INSTANCE;
                        bool2 = bool3;
                        templateSettings2 = templateSettings3;
                        str26 = str26;
                        str15 = decodeNullableSerializableElement32;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str21 = str19;
                        break;
                    case 20:
                        webViewSettings2 = webViewSettings3;
                        String str31 = str21;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement33 = beginStructure.decodeNullableSerializableElement(descriptor2, 20, StringSerializer.INSTANCE, str26);
                        i2 |= 1048576;
                        Unit unit22 = Unit.INSTANCE;
                        bool2 = bool3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str21 = str31;
                        str26 = decodeNullableSerializableElement33;
                        map3 = map5;
                        break;
                    case 21:
                        webViewSettings2 = webViewSettings3;
                        String str32 = str21;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str16 = str27;
                        Object decodeNullableSerializableElement34 = beginStructure.decodeNullableSerializableElement(descriptor2, 21, AdPayload$TemplateSettings$$serializer.INSTANCE, templateSettings3);
                        i2 |= 2097152;
                        Unit unit23 = Unit.INSTANCE;
                        bool2 = bool3;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        str21 = str32;
                        templateSettings2 = decodeNullableSerializableElement34;
                        map3 = map5;
                        break;
                    case 22:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str17 = str28;
                        Object decodeNullableSerializableElement35 = beginStructure.decodeNullableSerializableElement(descriptor2, 22, StringSerializer.INSTANCE, str27);
                        i2 |= 4194304;
                        Unit unit24 = Unit.INSTANCE;
                        str16 = decodeNullableSerializableElement35;
                        bool2 = bool3;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str21 = str19;
                        break;
                    case 23:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        obj11 = obj18;
                        Object decodeNullableSerializableElement36 = beginStructure.decodeNullableSerializableElement(descriptor2, 23, StringSerializer.INSTANCE, str28);
                        i2 |= 8388608;
                        Unit unit25 = Unit.INSTANCE;
                        str17 = decodeNullableSerializableElement36;
                        bool2 = bool3;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str21 = str19;
                        break;
                    case 24:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        adSizeInfo2 = adSizeInfo3;
                        num4 = num6;
                        Object decodeNullableSerializableElement37 = beginStructure.decodeNullableSerializableElement(descriptor2, 24, IntSerializer.INSTANCE, obj18);
                        i2 |= 16777216;
                        Unit unit26 = Unit.INSTANCE;
                        obj11 = decodeNullableSerializableElement37;
                        bool2 = bool3;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str17 = str28;
                        str21 = str19;
                        break;
                    case 25:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement38 = beginStructure.decodeNullableSerializableElement(descriptor2, 25, IntSerializer.INSTANCE, num6);
                        i2 |= TPMediaCodecProfileLevel.HEVCHighTierLevel62;
                        Unit unit27 = Unit.INSTANCE;
                        num4 = decodeNullableSerializableElement38;
                        bool2 = bool3;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        str21 = str19;
                        break;
                    case 26:
                        webViewSettings2 = webViewSettings3;
                        str19 = str21;
                        Object decodeNullableSerializableElement39 = beginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$AdSizeInfo$$serializer.INSTANCE, adSizeInfo3);
                        i2 |= AccessibilityEventCompat.TYPE_VIEW_TARGETED_BY_SCROLL;
                        Unit unit28 = Unit.INSTANCE;
                        adSizeInfo2 = decodeNullableSerializableElement39;
                        bool2 = bool3;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        str21 = str19;
                        break;
                    case 27:
                        str19 = str21;
                        webViewSettings2 = webViewSettings3;
                        Object decodeNullableSerializableElement40 = beginStructure.decodeNullableSerializableElement(descriptor2, 27, BooleanSerializer.INSTANCE, bool3);
                        i2 |= C.BUFFER_FLAG_FIRST_SAMPLE;
                        Unit unit29 = Unit.INSTANCE;
                        bool2 = decodeNullableSerializableElement40;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str21 = str19;
                        break;
                    case 28:
                        str19 = str21;
                        Object decodeNullableSerializableElement41 = beginStructure.decodeNullableSerializableElement(descriptor2, 28, AdPayload$WebViewSettings$$serializer.INSTANCE, webViewSettings3);
                        i2 |= 268435456;
                        Unit unit30 = Unit.INSTANCE;
                        webViewSettings2 = decodeNullableSerializableElement41;
                        map3 = map5;
                        str12 = str22;
                        str13 = str23;
                        str14 = str24;
                        list4 = list7;
                        viewAbility2 = viewAbility3;
                        str15 = str25;
                        templateSettings2 = templateSettings3;
                        str16 = str27;
                        str17 = str28;
                        obj11 = obj18;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool3;
                        str21 = str19;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                map5 = map3;
                list7 = list4;
                webViewSettings3 = webViewSettings2;
                templateSettings3 = templateSettings2;
                adSizeInfo3 = adSizeInfo2;
                num6 = num4;
                obj18 = obj11;
                str28 = str17;
                str27 = str16;
                bool3 = bool2;
                str25 = str15;
                viewAbility3 = viewAbility2;
                str24 = str14;
                str23 = str13;
                str22 = str12;
            }
            Object obj22 = obj12;
            AdPayload.WebViewSettings webViewSettings4 = webViewSettings3;
            str = str22;
            List list8 = list6;
            list = list7;
            str2 = str25;
            String str33 = str26;
            templateSettings = templateSettings3;
            String str34 = str27;
            bool = bool3;
            str3 = str29;
            i = i2;
            num2 = num5;
            obj = obj13;
            str4 = str20;
            obj2 = obj14;
            obj3 = obj15;
            obj4 = obj16;
            obj5 = obj17;
            str5 = str21;
            adSizeInfo = adSizeInfo3;
            num3 = num6;
            str6 = str28;
            str7 = str33;
            viewAbility = viewAbility3;
            list2 = list8;
            str8 = str24;
            str9 = str23;
            obj6 = obj22;
            obj7 = obj19;
            map = map5;
            webViewSettings = webViewSettings4;
            obj8 = obj18;
            str10 = str34;
        }
        beginStructure.endStructure(descriptor2);
        return new AdPayload.AdUnit(i, str3, str5, (String) obj7, (Integer) obj6, (String) obj5, (Boolean) obj3, (Boolean) obj4, (Boolean) obj2, str4, (String) obj, num, num2, map, str, str9, str8, list2, list, viewAbility, str2, str7, templateSettings, str10, str6, (Integer) obj8, num3, adSizeInfo, bool, webViewSettings, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.KSerializer, kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    @NotNull
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(@NotNull Encoder encoder, @NotNull AdPayload.AdUnit adUnit) {
        SerialDescriptor descriptor2 = getDescriptor();
        CompositeEncoder beginStructure = encoder.beginStructure(descriptor2);
        AdPayload.AdUnit.write$Self(adUnit, beginStructure, descriptor2);
        beginStructure.endStructure(descriptor2);
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] typeParametersSerializers() {
        return GeneratedSerializer.DefaultImpls.typeParametersSerializers(this);
    }
}
